Fitting models:   0%|          | 0/13 [00:00<?, ?it/s]Fitting models:   8%|▊         | 1/13 [00:01<00:12,  1.02s/it]Fitting models:  15%|█▌        | 2/13 [00:02<00:12,  1.13s/it]Fitting models:  23%|██▎       | 3/13 [00:17<01:15,  7.59s/it]Fitting models:  31%|███       | 4/13 [00:18<00:43,  4.82s/it]Fitting models:  38%|███▊      | 5/13 [00:22<00:36,  4.50s/it]Fitting models:  46%|████▌     | 6/13 [00:22<00:22,  3.17s/it]Fitting models:  54%|█████▍    | 7/13 [00:23<00:15,  2.56s/it]Fitting models:  62%|██████▏   | 8/13 [00:42<00:38,  7.63s/it]Fitting models:  69%|██████▉   | 9/13 [00:42<00:21,  5.39s/it]Fitting models:  77%|███████▋  | 10/13 [00:43<00:11,  3.89s/it]Fitting models:  85%|████████▍ | 11/13 [00:43<00:05,  2.77s/it]Fitting models:  92%|█████████▏| 12/13 [00:44<00:02,  2.09s/it]Fitting models: 100%|██████████| 13/13 [00:44<00:00,  1.54s/it]Fitting models: 100%|██████████| 13/13 [00:44<00:00,  3.42s/it]
Done:  J0328-0710
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:325: RuntimeWarning: invalid value encountered in scalar divide
  ea = abs(errors[2] / self.grad)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:326: RuntimeWarning: invalid value encountered in scalar divide
  eb = abs(errors[1] * (1.0 - eps) / self.grad)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:329: RuntimeWarning: invalid value encountered in scalar divide
  self.ellip_err = (abs(2.0 * errors[4] * (1.0 - eps) / self.sma
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:276: RuntimeWarning: invalid value encountered in scalar divide
  a = up_coeffs[1] / self.sma / abs(sample.gradient)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:277: RuntimeWarning: invalid value encountered in scalar divide
  b = up_coeffs[2] / self.sma / abs(sample.gradient)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:295: RuntimeWarning: invalid value encountered in scalar divide
  a_err = abs(a) * np.sqrt((ce[1] / up_coeffs[1])**2 + gre**2)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:296: RuntimeWarning: invalid value encountered in scalar divide
  b_err = abs(b) * np.sqrt((ce[2] / up_coeffs[2])**2 + gre**2)
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
Done: J0328-0710
/home/insepien/dualAGN/fit/plot_fit_with1d.py:86: RuntimeWarning: divide by zero encountered in divide
  return -2.5*np.log10(intensity/area)+ magZPT
/home/insepien/dualAGN/fit/plot_fit_with1d.py:157: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  pdf.savefig(bbox_inches='tight', pad_inches=0.2);
/home/insepien/dualAGN/fit/plot_fit_with1d.py:46: UserWarning: All values for SymLogScale are below linthresh, making it effectively linear. You likely should lower the value of linthresh. 
  [fig.colorbar(im[i], ax=ax[i], shrink=0.5).ax.yaxis.set_major_formatter(FormatStrFormatter('%.2f')) for i in range(len(ax))]
/home/insepien/dualAGN/fit/plot_fit_with1d.py:86: RuntimeWarning: divide by zero encountered in log10
  return -2.5*np.log10(intensity/area)+ magZPT
/home/insepien/dualAGN/fit/plot_fit_with1d.py:86: RuntimeWarning: invalid value encountered in log10
  return -2.5*np.log10(intensity/area)+ magZPT
/home/insepien/dualAGN/fit/plot_fit_with1d.py:110: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig = plt.figure(figsize=(14, 4),layout='tight')
Done:  J0328-0710
